# Change these first
owner: shirfan # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository
sites:
  - name: ilger.com
    url: https://www.ilger.com
    
  - name: KOS Site
    url: $KOS_SITE
    
  - name: KOS 02
    url: https://kos02.ilger.com
    
  - name: smtp2.ilger.com
    check: "tcp-ping"
    url: smtp2.ilger.it
    port: 25
    
  - name: test site
    url: http://iilllger.com/
    
  - name: vps.qweb.eu
    check: "tcp-ping"
    url: vps.qweb.eu
    port: 587
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: ilger.com
  name: ilger
  logoUrl: https://www.ilger.com/wp-content/uploads/2021/11/ILGER-logo.png
  baseUrl: /Uptime
  icon: https://www.ilger.com/wp-content/uploads/2022/03/ilger-logo-favicon.png
  introTitle: "Servers Uptime"
  introMessage: Status page which uses **real-time** data
  navbar:
    - title: Status
      href: /Uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
