# Change these first
owner: shirfan # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: ilger
    url: https://www.ilger.com
  - name: posta
    url: https://posta.ilger.com
  - name: Proxy1
    url: https://proxy1.ilger.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: ilger.com
  baseUrl: /Uptime
  logoUrl: https://www.ilger.com/wp-content/uploads/2021/11/ILGER-logo.png
  name: ilger
  introTitle: "Servers Uptime"
  introMessage: Status page which uses **real-time** data
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
